name: Local runner test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted]
    steps:
    - uses: actions/checkout@v2
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1.3.2
    - name: Display Terraform Version
      run: terraform --version
      shell: powershell