name: Local runner test

on:
  workflow_dispatch:

jobs:
  testRunner:
    runs-on: [self-hosted]
    defaults:
      run:
        shell: pwsh
    steps:
    - uses: actions/checkout@v2
    - name: Setup Terraform & Azure CLI
      run: choco install terraform azure-cli -y
    - name: Refresh Environment
      run: refreshenv
    - name: Display Terraform Version
      run: terraform version
    - name: Display Azure-CLI Version
      run: az version